"use client";
import React,{useEffect,useMemo,useState} from "react";
import { ArrowRightLeft, BarChart3, CheckCircle2, Clock3, KeyRound, Plus, Save, Search, ShieldCheck, UserCheck, UserX, Users, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { NeonBadge } from "@/components/ui/NeonBadge";
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));
const statusText=(s:string)=>({active:"فعال",on_leave:"مرخصی",inactive:"غیرفعال",transferred:"قطع همکاری",archived:"آرشیو",pending_offboarding:"در حال خروج"}[s]||s);
export const EmployeesView:React.FC=()=>{
 const [employees,setEmployees]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState<any|null>(null),[profile,setProfile]=useState<any>(),[customers,setCustomers]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[commissions,setCommissions]=useState<any[]>([]),[tab,setTab]=useState("overview"),[showCreate,setShowCreate]=useState(false),[showAccount,setShowAccount]=useState(false),[showTransfer,setShowTransfer]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<any>({code:"",name:"",firstName:"",lastName:"",mobile:"",phone:"",nationalId:"",avatarUrl:"",birthDate:"",address:"",description:"",cooperationType:"visitor",role:"visitor",status:"active",commissionRatePercent:5,baseSalary:0,startedAt:"",activityScope:"",managerId:""});
 const [account,setAccount]=useState({username:"",password:"",roleCode:"sales"}); const [transfer,setTransfer]=useState({toEmployeeId:"",projectId:"",reason:"انتقال پرونده"});
 const load=async()=>{setError("");try{const [e,p]=await Promise.all([fetch(`/api/employees?q=${encodeURIComponent(q)}${status?`&status=${status}`:""}`).then(r=>r.json()),fetch('/api/projects').then(r=>r.json())]);if(!e.success)throw Error(e.error);setEmployees(e.employees||[]);if(p.success)setProjects(p.projects||[])}catch(e:any){setError(e.message||"خطا")}};
 useEffect(()=>{load()},[q,status]);
 const open=async(emp:any)=>{setSelected(emp);setTab("overview");const [pr,c,s,cm]=await Promise.all([fetch(`/api/employees/${emp.id}/profile`).then(r=>r.json()),fetch(`/api/employees/${emp.id}/customers`).then(r=>r.json()),fetch(`/api/employees/${emp.id}/sales`).then(r=>r.json()),fetch(`/api/employees/${emp.id}/commissions`).then(r=>r.json())]);if(pr.success)setProfile(pr);if(c.success)setCustomers(c.customers||[]);if(s.success)setSales(s.sales||[]);if(cm.success)setCommissions(cm.commissions||[])};
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const r=await fetch('/api/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}).then(x=>x.json());if(!r.success)return alert(r.error);setShowCreate(false);load()}finally{setSaving(false)}};
 const createAccount=async()=>{if(!selected)return;setSaving(true);try{const r=await fetch(`/api/employees/${selected.id}/account`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(account)}).then(x=>x.json());if(!r.success)return alert(r.error);alert('حساب ورود ذخیره شد');setShowAccount(false)}finally{setSaving(false)}};
 const transferCustomers=async()=>{if(!selected||!transfer.toEmployeeId)return alert('همکار مقصد را انتخاب کن');const ids=customers.map(c=>c.id);if(!ids.length)return alert('مشتری فعال برای انتقال وجود ندارد');const r=await fetch(`/api/employees/${selected.id}/transfer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...transfer,customerIds:ids})}).then(x=>x.json());if(!r.success)return alert(r.error);alert(`${r.result?.transferred||0} مشتری منتقل شد`);setShowTransfer(false);open(selected)};
 const offboard=async()=>{if(!selected||!confirm('فرآیند خروج شروع شود؟ اطلاعات تاریخی حذف نمی‌شود.'))return;const r=await fetch(`/api/employees/${selected.id}/offboard`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({replacementEmployeeId:transfer.toEmployeeId||null,transferReason:'Offboarding از پنل'})}).then(x=>x.json());if(!r.success)return alert(r.error);alert('فرآیند خروج ثبت شد');setSelected(null);load()};
 const monthlySales=useMemo(()=>{const m=new Map<string,number>();for(const s of sales){const k=new Date(s.invoiceDate).toLocaleDateString('fa-IR',{year:'numeric',month:'2-digit'});m.set(k,(m.get(k)||0)+Number(s.grandTotal||0))}return Array.from(m.entries()).slice(-12).map(([month,value])=>({month,sales:value}))},[sales]);
 const monthlyCommission=useMemo(()=>{const m=new Map<string,number>();for(const c of commissions){const k=new Date(c.createdAt).toLocaleDateString('fa-IR',{year:'numeric',month:'2-digit'});m.set(k,(m.get(k)||0)+Number(c.commissionAmount||0))}return Array.from(m.entries()).slice(-12).map(([month,value])=>({month,commission:value}))},[commissions]);
 const summary=useMemo(()=>({active:employees.filter(e=>e.status==='active').length,off:employees.filter(e=>['transferred','archived'].includes(e.status)).length}),[employees]);
 return <div className="space-y-6">
  <div className="flex flex-col lg:flex-row gap-4 lg:items-center lg:justify-between"><div><h2 className="text-xl font-black text-white flex gap-2 items-center"><Users className="h-6 w-6 text-purple-400"/>همکاران</h2><p className="text-xs text-slate-400 mt-1">پرونده کامل، مشتری، فروش، پورسانت، پروژه، دسترسی، انتقال و Offboarding</p></div><button onClick={()=>{setForm({...form,code:`EMP-${Date.now().toString().slice(-6)}`});setShowCreate(true)}} className="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold flex gap-2"><Plus className="h-4 w-4"/>افزودن همکار</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">فعال</p><p className="text-2xl font-black text-emerald-300">{summary.active}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">خروج/آرشیو</p><p className="text-2xl font-black text-rose-300">{summary.off}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">مشتریان در نمای لیست</p><p className="text-2xl font-black text-cyan-300">{employees.reduce((a,e)=>a+Number(e.customerCount||0),0)||'-'}</p></div></div>
  <div className="flex flex-col md:flex-row gap-2"><div className="relative flex-1"><Search className="absolute right-3 top-2.5 h-4 w-4 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="نام، موبایل یا کد همکار" className="w-full rounded-xl bg-slate-900 border border-slate-800 px-9 py-2 text-xs text-white"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-xs text-white"><option value="">همه وضعیت‌ها</option><option value="active">فعال</option><option value="on_leave">مرخصی</option><option value="pending_offboarding">در حال خروج</option><option value="transferred">قطع همکاری</option><option value="archived">آرشیو</option></select></div>
  {error&&<div className="rounded-xl bg-rose-950/30 border border-rose-500/20 p-3 text-xs text-rose-300">{error}</div>}
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{employees.map(e=><button key={e.id} onClick={()=>open(e)} className="text-right rounded-2xl border border-slate-800 bg-slate-900/60 p-5 hover:border-purple-500/40 transition"><div className="flex justify-between"><div><span className="text-[10px] text-slate-500 font-mono">{e.code}</span><h3 className="font-bold text-white mt-1">{e.name}</h3><p className="text-xs text-purple-300 mt-1">{e.cooperationType} · {e.role}</p></div><NeonBadge variant={e.status==='active'?'green':e.status==='on_leave'?'yellow':e.status==='transferred'?'red':'gray'}>{statusText(e.status)}</NeonBadge></div><div className="mt-4 grid grid-cols-2 gap-2 text-[11px] text-slate-400"><span>موبایل: {e.mobile}</span><span>پورسانت: {Number(e.commissionRatePercent||0)}%</span><span>شروع: {e.startedAt?new Date(e.startedAt).toLocaleDateString('fa-IR'):'-'}</span><span>محدوده: {e.activityScope||'عمومی'}</span></div></button>)}</div>
  {selected&&<div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm p-3 md:p-6 overflow-y-auto"><div className="max-w-6xl mx-auto rounded-3xl bg-slate-950 border border-slate-800 p-5 md:p-7 space-y-5"><div className="flex justify-between"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-gradient-to-br from-purple-600 to-cyan-500 flex items-center justify-center"><UserCheck/></div><div><h3 className="text-xl font-black text-white">{selected.name}</h3><p className="text-xs text-slate-500">{selected.code} · {selected.mobile} · {statusText(selected.status)}</p></div></div><button onClick={()=>setSelected(null)}><X className="text-slate-400"/></button></div>
   <div className="flex gap-2 overflow-x-auto border-b border-slate-800 pb-2">{[["overview","نمای کلی",BarChart3],["customers","مشتریان",Users],["sales","فروش",BarChart3],["commission","پورسانت",DollarSign],["projects","پروژه‌ها",FolderKanban],["timeline","Timeline",Clock3],["access","دسترسی",ShieldCheck]].map(([id,l,I]:any)=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg text-xs whitespace-nowrap flex gap-2 ${tab===id?'bg-purple-600 text-white':'text-slate-400 hover:bg-slate-900'}`}><I className="h-4 w-4"/>{l}</button>)}</div>
   {tab==='overview'&&<div className="space-y-5">{profile?.reports&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[["فروش امروز",profile.reports.today.todaySales],["فروش ماه",profile.reports.month.periodSales],["فروش سال",profile.reports.year.periodSales],["مشتری",profile.reports.month.customers],["پورسانت ماه",profile.reports.month.periodCommission],["پرداخت‌نشده",profile.reports.month.unpaidCommission]].map(([l,v]:any)=><div key={l} className="rounded-xl bg-slate-900 p-3"><p className="text-[10px] text-slate-500">{l}</p><b>{money(Number(v)||0)}</b></div>)}</div>}<div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold mb-4">روند فروش</h4><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlySales}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="month" stroke="#64748b" fontSize={10}/><YAxis stroke="#64748b" fontSize={10}/><Tooltip/><Line type="monotone" dataKey="sales" stroke="#a78bfa" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold mb-4">روند پورسانت</h4><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyCommission}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="month" stroke="#64748b" fontSize={10}/><YAxis stroke="#64748b" fontSize={10}/><Tooltip/><Bar dataKey="commission" fill="#22d3ee"/></BarChart></ResponsiveContainer></div></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowAccount(true)} className="rounded-xl bg-slate-800 px-3 py-2 text-xs flex gap-2"><KeyRound className="h-4 w-4"/>حساب ورود</button><button onClick={()=>setShowTransfer(true)} className="rounded-xl bg-amber-950/40 border border-amber-500/20 px-3 py-2 text-xs text-amber-300 flex gap-2"><ArrowRightLeft className="h-4 w-4"/>انتقال مشتریان</button><button onClick={offboard} className="rounded-xl bg-rose-950/40 border border-rose-500/20 px-3 py-2 text-xs text-rose-300 flex gap-2"><UserX className="h-4 w-4"/>شروع Offboarding</button></div></div>}
   {tab==='customers'&&<div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full text-xs"><thead><tr className="text-slate-500"><th className="p-3 text-right">مشتری</th><th className="p-3">موبایل</th><th className="p-3">سلامت</th><th className="p-3">وضعیت</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="p-3">{c.storeName||c.name}</td><td className="p-3">{c.mobile}</td><td className="p-3">{c.healthScore}</td><td className="p-3"><NeonBadge variant={c.status==='active'?'green':'gray'}>{c.status}</NeonBadge></td></tr>)}</tbody></table></div>}
   {tab==='sales'&&<div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full text-xs"><thead><tr className="text-slate-500"><th className="p-3 text-right">فاکتور</th><th className="p-3">تاریخ</th><th className="p-3">مبلغ</th><th className="p-3">وضعیت</th></tr></thead><tbody>{sales.map(s=><tr key={s.id} className="border-t border-slate-800"><td className="p-3 font-mono">{s.invoiceNumber}</td><td className="p-3">{new Date(s.invoiceDate).toLocaleDateString('fa-IR')}</td><td className="p-3">{money(Number(s.grandTotal||0))}</td><td className="p-3">{s.paymentStatus}</td></tr>)}</tbody></table></div>}
   {tab==='commission'&&<div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full text-xs"><thead><tr className="text-slate-500"><th className="p-3 text-right">مبلغ</th><th className="p-3">مبنا</th><th className="p-3">وضعیت</th><th className="p-3">تاریخ</th></tr></thead><tbody>{commissions.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="p-3">{money(Number(c.commissionAmount||0))}</td><td className="p-3">{money(Number(c.baseAmount||0))}</td><td className="p-3">{c.status}</td><td className="p-3">{new Date(c.createdAt).toLocaleDateString('fa-IR')}</td></tr>)}</tbody></table></div>}
   {tab==='projects'&&<div className="grid md:grid-cols-2 gap-3">{(profile?.projects||[]).map((p:any)=><div key={p.assignment.id} className="rounded-2xl border border-slate-800 p-4"><div className="flex justify-between"><b>{p.project?.name||'-'}</b><NeonBadge variant={p.assignment.status==='active'?'green':'gray'}>{p.assignment.status}</NeonBadge></div><p className="text-xs text-slate-500 mt-2">نقش: {p.assignment.role} · پورسانت: {p.assignment.commissionRate??'-'}% · حقوق پروژه: {money(Number(p.assignment.projectSalary||0))}</p></div>)}{!(profile?.projects||[]).length&&<p className="text-slate-500">پروژه‌ای ثبت نشده است.</p>}</div>}
   {tab==='timeline'&&<div className="space-y-2">{(profile?.activity||[]).map((a:any)=><div key={a.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between"><b className="text-xs">{a.action}</b><span className="text-[10px] text-slate-500">{new Date(a.createdAt).toLocaleString('fa-IR')}</span></div><p className="text-xs text-slate-400 mt-1">{a.details?.reason||a.details?.event||a.entityType}</p></div>)}{!(profile?.activity||[]).length&&<p className="text-slate-500">Timeline خالی است.</p>}</div>}
   {tab==='access'&&<div className="rounded-2xl border border-slate-800 p-4 space-y-3"><p className="text-xs text-slate-400">دسترسی‌ها از Role و Project Scope خوانده می‌شوند و به صورت واقعی توسط API کنترل می‌شوند.</p><div className="flex flex-wrap gap-2">{['customers.view','customers.create','customers.update','customers.transfer','invoices.view','commissions.view','reports.view','projects.view','projects.update','payments.create'].map(x=><span key={x} className="rounded-lg bg-slate-900 border border-slate-800 px-2 py-1 text-[10px]">{x}</span>)}</div></div>}
   <div className="flex justify-end"><button onClick={()=>setSelected(null)} className="rounded-xl border border-slate-700 px-4 py-2 text-xs">بستن</button></div>
  </div></div>}
  {showCreate&&<div className="fixed inset-0 z-[60] bg-black/80 flex items-center justify-center p-4"><form onSubmit={create} className="w-full max-w-4xl max-h-[90vh] overflow-auto rounded-3xl bg-slate-950 border border-slate-800 p-6 space-y-4"><div className="flex justify-between"><h3 className="text-lg font-bold">پرونده کامل همکار</h3><button type="button" onClick={()=>setShowCreate(false)}><X/></button></div><div className="grid md:grid-cols-2 gap-3">{[['code','کد'],['name','نام کامل'],['firstName','نام'],['lastName','نام خانوادگی'],['mobile','موبایل'],['phone','تماس دوم'],['nationalId','کد ملی'],['address','آدرس'],['activityScope','محدوده فعالیت'],['baseSalary','حقوق پایه'],['commissionRatePercent','پورسانت پیش‌فرض']].map(([k,l])=><label key={k} className="text-xs text-slate-400">{l}<input value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-white"/></label>)}<label className="text-xs text-slate-400">نوع همکاری<select value={form.cooperationType} onChange={e=>setForm({...form,cooperationType:e.target.value})} className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-white">{[['employee','کارمند'],['visitor','ویزیتور'],['seller','فروشنده'],['representative','نماینده'],['project','همکار پروژه‌ای'],['independent','مستقل'],['other','سایر']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="text-xs text-slate-400">نقش<input value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-white"/></label></div><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="توضیحات" className="w-full h-24 rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"/><div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-purple-600 px-5 py-2 text-xs font-bold flex gap-2"><Save className="h-4 w-4"/>{saving?'ذخیره…':'ثبت همکار'}</button></div></form></div>}
  {showAccount&&<div className="fixed inset-0 z-[70] bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-3xl bg-slate-950 border border-slate-800 p-6 space-y-4"><h3 className="font-bold">حساب ورود همکار</h3><input value={account.username} onChange={e=>setAccount({...account,username:e.target.value})} placeholder="Username / Mobile" className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"/><input type="password" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})} placeholder="Password" className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"/><select value={account.roleCode} onChange={e=>setAccount({...account,roleCode:e.target.value})} className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"><option value="sales">فروش</option><option value="manager">مدیر</option><option value="accountant">حسابدار</option></select><div className="flex justify-end gap-2"><button onClick={()=>setShowAccount(false)} className="rounded-xl px-4 py-2 text-xs">لغو</button><button onClick={createAccount} className="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold">ذخیره</button></div></div></div>}
  {showTransfer&&<div className="fixed inset-0 z-[70] bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-3xl bg-slate-950 border border-slate-800 p-6 space-y-4"><h3 className="font-bold">انتقال پرونده مشتریان</h3><p className="text-xs text-slate-400">قبل از انتقال: {customers.length} مشتری، سفارش/فاکتور و تاریخچه در سیستم باقی می‌مانند.</p><select value={transfer.toEmployeeId} onChange={e=>setTransfer({...transfer,toEmployeeId:e.target.value})} className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"><option value="">همکار مقصد</option>{employees.filter(e=>e.id!==selected?.id&&e.status==='active').map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><select value={transfer.projectId} onChange={e=>setTransfer({...transfer,projectId:e.target.value})} className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"><option value="">پروژه مقصد (اختیاری)</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><textarea value={transfer.reason} onChange={e=>setTransfer({...transfer,reason:e.target.value})} className="w-full rounded-xl bg-slate-900 border border-slate-800 p-3 text-white h-20"/><div className="flex justify-end"><button onClick={transferCustomers} className="rounded-xl bg-amber-600 px-4 py-2 text-xs font-bold flex gap-2"><ArrowRightLeft className="h-4 w-4"/>تأیید انتقال</button></div></div></div>}
 </div>
}
