"use client";
import React,{useEffect,useMemo,useState} from "react";
import { Archive, BarChart3, Clock3, DollarSign, FolderKanban, MapPin, Plus, Save, Settings2, Target, TrendingUp, Users, Wallet, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { NeonBadge } from "@/components/ui/NeonBadge";
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));
const statusLabel=(s:string)=>({active:"فعال",paused:"متوقف موقت",completed:"پایان‌یافته",archived:"آرشیو"}[s]||s);
export const ProjectManagementView:React.FC=()=>{
 const [projects,setProjects]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[tab,setTab]=useState("overview"),[dashboard,setDashboard]=useState<any>(),[analytics,setAnalytics]=useState<any>(),[customers,setCustomers]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[form,setForm]=useState<any>({code:"",name:"",label:"",description:"",color:"#3b82f6",status:"active",managerEmployeeId:"",independentSalesAllowed:false,targetMonthlySales:0,targetYearlySales:0,targetCustomerCount:0,targetProfit:0,targetCollection:0});
 const load=async()=>{setLoading(true);setError("");try{const [p,e]=await Promise.all([fetch("/api/projects").then(r=>r.json()),fetch("/api/employees").then(r=>r.json())]);if(!p.success)throw Error(p.error);setProjects(p.projects||[]);if(e.success)setEmployees(e.employees||[]);}catch(e:any){setError(e.message||"خطا در دریافت پروژه‌ها")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const openProject=async(p:any)=>{setSelected(p);setTab("overview");const [d,a,c,m,act]=await Promise.all([fetch(`/api/projects/${p.id}/dashboard`).then(r=>r.json()),fetch(`/api/projects/${p.id}/analytics`).then(r=>r.json()),fetch(`/api/projects/${p.id}/customers`).then(r=>r.json()),fetch(`/api/projects/${p.id}/employees`).then(r=>r.json()),fetch(`/api/projects/${p.id}/activity`).then(r=>r.json())]);if(d.success)setDashboard(d.dashboard);if(a.success)setAnalytics(a.analytics);if(c.success)setCustomers(c.customers||[]);if(m.success)setMembers(m.members||[]);if(act.success)setActivity(act.activity||[])};
 const openCreate=()=>{setForm({code:`PRJ-${Date.now().toString().slice(-6)}`,name:"",label:"",description:"",color:"#3b82f6",status:"active",managerEmployeeId:"",independentSalesAllowed:false,targetMonthlySales:0,targetYearlySales:0,targetCustomerCount:0,targetProfit:0,targetCollection:0});setShow(true)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}).then(x=>x.json());if(!r.success)return alert(r.error);setShow(false);load()};
 const archive=async()=>{if(!selected||!confirm("پروژه آرشیو شود؟ هیچ اطلاعاتی حذف نمی‌شود."))return;const r=await fetch(`/api/projects/${selected.id}`,{method:"DELETE"}).then(x=>x.json());if(!r.success)return alert(r.error);setSelected(null);load()};
 const stats=useMemo(()=>({active:projects.filter(p=>p.status==='active').length,archived:projects.filter(p=>p.status==='archived').length}),[projects]);
 if(loading)return <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-8 text-center text-slate-400">در حال بارگذاری پروژه‌ها…</div>;
 if(error)return <div className="rounded-3xl border border-rose-500/20 bg-rose-950/20 p-8 text-center text-rose-300">{error}<button className="block mx-auto mt-4 rounded-xl bg-slate-800 px-4 py-2 text-xs" onClick={load}>تلاش مجدد</button></div>;
 return <div className="space-y-6">
  <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="text-xl font-extrabold text-white flex items-center gap-2"><FolderKanban className="h-6 w-6 text-cyan-400"/>پروژه‌ها</h2><p className="text-xs text-slate-400 mt-1">Scope واقعی فروش، مشتری، همکار، قیمت، پورسانت، موجودی و گزارش</p></div><button onClick={openCreate} className="rounded-xl bg-cyan-600 px-4 py-2 text-xs font-bold flex gap-2"><Plus className="h-4 w-4"/>ایجاد پروژه</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">فعال</p><p className="text-2xl font-black">{stats.active}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">آرشیو</p><p className="text-2xl font-black">{stats.archived}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">کل</p><p className="text-2xl font-black">{projects.length}</p></div></div>
  {projects.length===0?<div className="rounded-3xl border border-dashed border-slate-700 p-12 text-center text-slate-400">هنوز پروژه‌ای ثبت نشده است.</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{projects.map(p=><button key={p.id} onClick={()=>openProject(p)} className="text-right rounded-2xl border border-slate-800 bg-slate-900/60 p-5 hover:border-cyan-500/50 transition"><div className="flex justify-between"><div><span className="font-mono text-[10px] text-slate-500">{p.code}</span><h3 className="font-bold text-white mt-1">{p.name}</h3></div><span className="h-9 w-9 rounded-xl" style={{background:p.color||'#3b82f6',boxShadow:`0 0 20px ${p.color||'#3b82f6'}66`}}/></div><div className="mt-3 flex gap-2"><NeonBadge variant={p.status==='active'?'green':p.status==='paused'?'yellow':p.status==='archived'?'gray':'blue'}>{statusLabel(p.status)}</NeonBadge>{p.label&&<span className="text-[11px] text-slate-400">{p.label}</span>}</div><div className="grid grid-cols-2 gap-2 mt-4 text-[11px] text-slate-400"><span>هدف ماه: {money(Number(p.targetMonthlySales||0))}</span><span>هدف سال: {money(Number(p.targetYearlySales||0))}</span><span>هدف مشتری: {Number(p.targetCustomerCount||0)}</span><span>فروش مستقل: {p.independentSalesAllowed?'بله':'خیر'}</span></div></button>)}</div>}
  {selected&&<div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm p-3 md:p-6 overflow-y-auto"><div className="max-w-6xl mx-auto rounded-3xl bg-slate-950 border border-slate-800 p-5 md:p-7 space-y-5"><div className="flex justify-between"><div className="flex gap-3 items-center"><span className="h-11 w-11 rounded-xl" style={{background:selected.color||'#3b82f6',boxShadow:`0 0 24px ${selected.color||'#3b82f6'}66`}}/><div><h3 className="text-xl font-black text-white">{selected.name}</h3><p className="text-xs text-slate-500 font-mono">{selected.code} · {statusLabel(selected.status)}</p></div></div><button onClick={()=>setSelected(null)}><X className="text-slate-400"/></button></div>
    <div className="flex gap-2 overflow-x-auto border-b border-slate-800 pb-2">{[["overview","نمای کلی",BarChart3],["customers","مشتریان",Users],["employees","همکاران",Users],["map","نقشه",MapPin],["targets","اهداف",Target],["activity","Timeline",Clock3],["settings","تنظیمات",Settings2]].map(([id,label,I]:any)=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg text-xs whitespace-nowrap flex gap-2 ${tab===id?'bg-cyan-600 text-white':'text-slate-400 hover:bg-slate-900'}`}><I className="h-4 w-4"/>{label}</button>)}</div>
    {tab==='overview'&&<div className="space-y-5">{dashboard&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[["فروش",dashboard.sales],["سود ناخالص",dashboard.grossProfit],["سود خالص",dashboard.netProfit],["پورسانت",dashboard.commission],["وصولی",dashboard.collected],["فاکتور",dashboard.invoices]].map(([l,v]:any)=><div key={l} className="rounded-xl bg-slate-900 p-3"><p className="text-[10px] text-slate-500">{l}</p><b className="text-white">{typeof v==='number'?money(v):v}</b></div>)}</div>}<div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold mb-4">روند فروش ۱۲ ماهه</h4><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics?.monthlySales||[]}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="month" stroke="#64748b" fontSize={10}/><YAxis stroke="#64748b" fontSize={10}/><Tooltip/><Line type="monotone" dataKey="sales" stroke="#22d3ee" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold mb-4">فروش به تفکیک محصول</h4><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics?.products||[]}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="name" stroke="#64748b" fontSize={9}/><YAxis stroke="#64748b" fontSize={10}/><Tooltip/><Bar dataKey="sales" fill="#8b5cf6"/></BarChart></ResponsiveContainer></div></div></div><div className="grid md:grid-cols-3 gap-4"><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold flex gap-2"><DollarSign className="h-4 w-4"/>P&amp;L</h4><p className="text-xs text-slate-400 mt-3">هزینه: {money(analytics?.expense||0)}</p><p className="text-xs text-slate-400">مطالبات: {money(analytics?.receivable||0)}</p><p className="text-xs text-slate-400">وصولی: {money(analytics?.paid||0)}</p></div><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold flex gap-2"><Wallet className="h-4 w-4"/>Cash Flow</h4><p className="text-xs text-slate-400 mt-3">وصولی ثبت‌شده: {money(analytics?.paid||0)}</p><p className="text-xs text-slate-400">پورسانت پرداختی: {money(analytics?.commissionsPaid||0)}</p></div><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold flex gap-2"><TrendingUp className="h-4 w-4"/>Forecast / What-If</h4><p className="text-xs text-slate-400 mt-3">از API تحلیلی پروژه قابل محاسبه و مستقل از داده واقعی است.</p><button onClick={async()=>{const r=await fetch(`/api/projects/analytics?projectId=${selected.id}&mode=whatif&priceDelta=10&salesDelta=-5&commissionDelta=2`).then(x=>x.json());if(r.success)alert(`سناریوی نمونه\nفروش: ${money(r.scenario.revenue)}\nسود: ${money(r.scenario.netProfit)}`)}} className="mt-3 rounded-lg bg-slate-800 px-3 py-2 text-xs">اجرای سناریوی +۱۰٪ قیمت / -۵٪ فروش</button></div></div></div>}
    {tab==='customers'&&<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{['green','yellow','red','gray'].map(s=><div key={s} className="rounded-xl bg-slate-900 p-3 text-xs text-slate-400">{s==='green'?'سبز':s==='yellow'?'زرد':s==='red'?'قرمز':'سایر'}: {customers.filter(c=>c.healthStatus===s).length}</div>)}</div><div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full text-xs"><thead><tr className="text-slate-500"><th className="p-3 text-right">مشتری</th><th className="p-3">موبایل</th><th className="p-3">همکار</th><th className="p-3">سلامت</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="p-3">{c.storeName||c.name}</td><td className="p-3 text-slate-400">{c.mobile}</td><td className="p-3 text-slate-400">{c.employeeName}</td><td className="p-3"><NeonBadge variant={c.healthStatus==='green'?'green':c.healthStatus==='yellow'?'yellow':'red'}>{c.healthScore}</NeonBadge></td></tr>)}</tbody></table></div></div>}
    {tab==='employees'&&<div className="grid md:grid-cols-2 gap-3">{members.map((m:any)=><div key={m.assignment.id} className="rounded-2xl border border-slate-800 p-4"><div className="flex justify-between"><div><b>{m.employee.name}</b><p className="text-xs text-slate-500">{m.assignment.role}</p></div><NeonBadge variant={m.assignment.status==='active'?'green':'gray'}>{m.assignment.status}</NeonBadge></div><div className="grid grid-cols-2 gap-2 mt-3 text-xs text-slate-400"><span>پورسانت: {m.assignment.commissionRate??'-'}%</span><span>حقوق پروژه: {money(Number(m.assignment.projectSalary||0))}</span></div></div>)}{!members.length&&<div className="text-sm text-slate-500">همکاری برای این پروژه ثبت نشده است.</div>}</div>}
    {tab==='map'&&<div className="space-y-4"><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{customers.map((c:any)=><a key={c.id} href={`https://www.openstreetmap.org/?mlat=${c.latitude}&mlon=${c.longitude}#map=17/${c.latitude}/${c.longitude}`} target="_blank" rel="noreferrer" className="rounded-xl bg-slate-950 border border-slate-800 p-3 hover:border-cyan-500/40"><div className="flex gap-2 items-center"><MapPin className="h-4 w-4 text-cyan-400"/><span className="text-xs font-bold">{c.storeName||c.name}</span></div><p className="text-[10px] text-slate-500 mt-2">{c.latitude}, {c.longitude}</p><span className="text-[10px] text-cyan-300 mt-2 inline-block">باز کردن روی نقشه</span></a>)}</div></div><p className="text-[11px] text-slate-500">مختصات از Customer واقعی گرفته می‌شود؛ برای جلوگیری از وابستگی به کلید نقشه، هر مشتری مستقیماً روی OpenStreetMap باز می‌شود.</p></div>}
    {tab==='targets'&&<div className="grid md:grid-cols-2 gap-4"><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold">اهداف فعلی</h4><div className="space-y-3 mt-4 text-xs">{[["فروش ماهانه",Number(selected.targetMonthlySales||0),dashboard?.sales||0],["فروش سالانه",Number(selected.targetYearlySales||0),dashboard?.sales||0],["مشتری",Number(selected.targetCustomerCount||0),dashboard?.customers||0],["سود",Number(selected.targetProfit||0),dashboard?.grossProfit||0]].map(([l,t,a]:any)=><div key={l}><div className="flex justify-between"><span>{l}</span><span>{money(a)} / {money(t)}</span></div><div className="mt-1 h-2 rounded bg-slate-800 overflow-hidden"><div className="h-full bg-cyan-500" style={{width:`${Math.min(100,t? a/t*100:0)}%`}}/></div></div>)}</div></div></div>}
    {tab==='activity'&&<div className="space-y-2">{activity.map((a:any)=><div key={a.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between"><b className="text-xs">{a.action}</b><span className="text-[10px] text-slate-500">{new Date(a.createdAt).toLocaleString('fa-IR')}</span></div><p className="text-[11px] text-slate-400 mt-1">{a.details?.reason||a.details?.event||a.entityType}</p></div>)}{!activity.length&&<div className="text-slate-500 text-sm">Timeline خالی است.</div>}</div>}
    {tab==='settings'&&<div className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold">هویت پروژه</h4><p className="text-xs text-slate-400 mt-2">رنگ: {selected.color} · Label: {selected.label||'-'}</p><p className="text-xs text-slate-400">مدیر: {employees.find(e=>e.id===selected.managerEmployeeId)?.name||'بدون مدیر'}</p></div><div className="rounded-2xl border border-slate-800 p-4"><h4 className="font-bold">قوانین</h4><p className="text-xs text-slate-400 mt-2">فروش مستقل: {selected.independentSalesAllowed?'فعال':'غیرفعال'}</p><p className="text-xs text-slate-400">تغییرات اصلی در Audit ثبت می‌شوند.</p></div></div><button onClick={archive} className="rounded-xl border border-rose-500/30 px-4 py-2 text-xs text-rose-300 flex gap-2"><Archive className="h-4 w-4"/>آرشیو امن پروژه</button></div>}
    </div></div>}
  {show&&<div className="fixed inset-0 z-[60] bg-black/80 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-3xl rounded-3xl bg-slate-950 border border-slate-800 p-6 space-y-4"><div className="flex justify-between"><h3 className="text-lg font-bold">ایجاد پروژه</h3><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="grid md:grid-cols-2 gap-3">{[['code','کد'],['name','نام'],['label','Label'],['targetMonthlySales','هدف فروش ماه'],['targetYearlySales','هدف فروش سال'],['targetCustomerCount','هدف مشتری'],['targetProfit','هدف سود'],['targetCollection','هدف وصول']].map(([k,l])=><label key={k} className="text-xs text-slate-400">{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-white"/></label>)}<label className="text-xs text-slate-400">مدیر<select value={form.managerEmployeeId} onChange={e=>setForm({...form,managerEmployeeId:e.target.value})} className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-800 px-3 py-2 text-white"><option value="">بدون مدیر</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="text-xs text-slate-400">رنگ<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})} className="mt-1 h-10 w-full rounded-xl bg-slate-900"/></label><label className="md:col-span-2 text-xs text-slate-400">توضیحات<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full h-24 rounded-xl bg-slate-900 border border-slate-800 p-3 text-white"/></label></div><label className="flex gap-2 text-xs"><input type="checkbox" checked={form.independentSalesAllowed} onChange={e=>setForm({...form,independentSalesAllowed:e.target.checked})}/> فروش مستقل مجاز باشد</label><div className="flex justify-end"><button className="rounded-xl bg-cyan-600 px-5 py-2 font-bold flex gap-2"><Save className="h-4 w-4"/>ثبت پروژه</button></div></form></div>}
 </div>
}
